# SPDX-License-Identifier: LGPL-2.1-or-later
# Debian ARM64 for Snapdragon X Elite.
# Requires debian unstable for kernel >= 6.12 (x1e80100 DTB support).

[Match]
Distribution=debian
Architecture=arm64

[Distribution]
Release=unstable

[Content]
Packages=
        linux-image-arm64
        linux-headers-arm64
        firmware-qcom-soc
        firmware-linux-nonfree
        tpm2-tools
        tpm2-abrmd
        sbctl
