# SPDX-License-Identifier: LGPL-2.1-or-later
# Fedora ARM64 for Snapdragon X Elite.
# Fedora rawhide aarch64 ships x1e80100-microsoft-romulus13/15.dtb since kernel 6.12.
# Source: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/arch/arm64/boot/dts/qcom/x1e80100-microsoft-romulus13.dts

[Match]
Distribution=fedora
Architecture=arm64

[Content]
Packages=
        kernel-core
        kernel-modules
        kernel-modules-extra
        qrtr-tools
        pd-mapper
        linux-firmware
