# SPDX-License-Identifier: LGPL-2.1-or-later
# Surface Laptop 7 audio DSP additions for Snapdragon X Elite
# Extends the base surface-arm64 profile.

[Match]
Profile=surface-arm64

[Content]
# Qualcomm LPASS/Q6DSP audio stack
Packages=
        alsa-utils
        alsa-ucm-conf
        pipewire
        wireplumber
        pipewire-pulseaudio
